---
- name: configure static website
  hosts: all
  become: true
  tasks:


  #clone git repo
  - name: clone repo
    git:
      repo: https://github.com/waleedKotyb/jenkins-examples.git
      dest: /home/ubuntu/swebsite
  #install apache
  - name: install apache
    apt:
      name: apache2

      
  - name: activate apache
    service:
      name: apache2
      state: started

  #copy repo files  to apache default dir. -> /var/www/html
  - name: copy site files
    copy:
      src: /home/ubuntu/swebsite/CICD-static-website-on-apache/edu-website/
      dest: /var/www/html/
      remote_src: true
    

   #configure ufw to allow http,ssh
  - name: configure firewall
    ufw:
      state: enabled
      rule: allow
      port: 80
      rule: allow
      port: 22
